server:
  port: 8084

spring:
  cloud:
    gateway:
#      discovery.locator:
#        enabled: true
#        lower-case-service-id: true
      routes:
      - id: organization-service
        uri: lb://organization-service
        predicates:
          - Path=/organization/**
        filters:
          - RewritePath=/organization/(?<path>.*), /$\{path}
      - id: licensing-service
        uri: lb://licensing-service
        predicates:
          - Path=/license/**
        filters:
          - RewritePath=/license/(?<path>.*), /$\{path}
