server:
  port: 8084

spring:
  cloud:
    gateway:
#      discovery.locator:
#        enabled: true
#        lower-case-service-id: true
      routes:
      - id: organization-service
        uri: lb://organization-service
        predicates:
          - Path=/organization/**
        filters:
          - RewritePath=/organization/(?<path>.*), /$\{path}

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8082/eureka/